// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SombrancelhaApp.Api.Infrastructure.Data;

#nullable disable

namespace SombrancelhaApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110000706_AddConfirmacaoLimpeza")]
    partial class AddConfirmacaoLimpeza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SombrancelhaApp.Api.Domain.AtendimentoSimulacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AvisadoSobreExpiracao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoImagemFinal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfirmadoParaDeletar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMolde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImagemFinal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AtendimentoSimulacoes");
                });

            modelBuilder.Entity("SombrancelhaApp.Api.Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("SombrancelhaApp.Api.Domain.ClienteImagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClienteImagens");
                });
#pragma warning restore 612, 618
        }
    }
}
